{
  "name": { "type": "string", "default": "file" },
  "namespace": { "type": "string", "default": "schemas" },
  "prefix": { "type": "string", "default": "file" },
  "label": { "type": "string", "default": "FILE" },
  "kind": { "type": "string", "default": "node" },
  "keys":
    {
      "required": True,
      "type": "list",
      "default": ["label", "name", "file_type"],
    },
  "props":
    {
      "required": True,
      "type": "dict",
      "schema":
        {
          "__id": { "type": "string", "default": "str" },
          "label": { "type": "string", "required": True, "default": "str" },
          "name": { "type": "string", "required": True, "default": "str" },
          "item_prefix":
            { "type": "string", "required": True, "default": "file" },
          "file_type": { "type": "string", "required": True, "default": "str" },
          "size": { "type": "integer", "required": True, "default": "integer" },
          "doc": { "type": "string", "default": "str" },
        },
    },
}
